### PR TITLE
25 order controller

### LINKED ISSUE #25: Order controller
Create order controller.

### PR DESCRIPTION
**Pull request by zehraworks**
- created getCookAssignedOrders and payment controllers for order
- created routes and middlewares for order
- added status field in OrderItemSchema and user field in OrderSchema ( each item's status can change by the cook. )
- remove status from checkout in cart controller ( when cart checkout, the order will be created automatically by default "waiting" status. )
- configured eslint ( it is necessary to use _id to get dish's id and also another config for spread operator. )

### CODE REVIEW

**Review by OmarQaqish — APPROVED** [review]
This looks great, thank you @aydinfz, but I think later we should have the checkout controller redirect to 'api/order/payment/:orderId' so that when the customer places an order, they're automatically redirected to the payment route.

**Comment by zehraworks** [comment]
When a customer checkout, the order status will be waiting, then if he decided to pay he will send the request to "api/order/payment/:orderId". Otherwise, no need to use 2 endpoints we can directly make the status as paid by only one endpoint. But normally payment needs some kind of way maybe like Paypal or credit cart. After the customer selects a method from these payment methods, he pays. This is the scenario in my mind. I'm open to any feedback @OmarQaqish @tarik310

**Comment by OmarQaqish** [comment]
> When a customer checkout, the order status will be waiting, then if he decided to pay he will send the request to "api/order/payment/:orderId". Otherwise, no need to use 2 endpoints we can directly make the status as paid by only one endpoint. But normally payment needs some kind of way maybe like Paypal or credit cart. After the customer selects a method from these payment methods, he pays. This is the scenario in my mind. I'm open to any feedback @OmarQaqish @tarik310

Yes, this makes sense.

**Review by tarik310 — APPROVED** [review]

**Comment by tarik310** [comment]
great work Zehra

**Pull request merged**
