### PR TITLE
Tarik310/issue47

### LINKED ISSUE #47: User Signin / Signup
create normal sign in up

### PR DESCRIPTION
**Pull request by tarik310**
created the signIn/up authentication controllers close #47 

- [x] updated the routes of the users.
- [x] created a separate routes for user and cook
- [x] implemented the authentication middleware to protect routes
- [x] implemented the authorization middleware to restrict access of some routes.

**NOTES**
the signout controller isn't implemented yet because we need to use client storage (session or cookie) to store jwt token and control it.
for now I was just sending the token in the headers of the requests to test the code.

### CODE REVIEW

**Review by OmarQaqish — COMMENTED** [review]
Hello @tarik310 Thank you very much for your hard work. This looks great, however, I have some comments and questions:

1. Let's please stick to camel case naming convention in naming the controller functions, so signIn, signUp, and signOut instead of SignIn, SignUp, and SignOut.
2. We should probably move the restrictTo and protectRoute middlewares to their own file, maybe in a middleware folder.
3. In models/user.js, where did we get the JWTTIMESTAMP variable from?
4. I think your way of using a custom method to generate a token in the model and calling it in the sign in functionality is a good way of doing this instead of including the whole logic of generating a token in the controllers.

I will keep looking into the code, but for now, this is what I have.

**Comment by zehraworks** [comment]
- What's the purpose of saving the token in database?
- I agree with Omar about creating middleware folder for restrictTo and protectRoute.
- ```const decoded = jwt.verify(token, process.env.JWT_SECRET);```  jwt verify should cover with try/catch, try/catch makes it still run even if any error occurs

**Comment by tarik310** [comment]
the JWTTIMESTAMP is just an argument for the changedPasswordAfter function. actually th's function is not necessary and it used for security purpose as when the jwt won't be valid after changing the password.
I'll fix the the problems you guys mentioned and add a middleware folder and necessary files

**Comment by OmarQaqish** [comment]
> the JWTTIMESTAMP is just an argument for the changedPasswordAfter function. actually th's function is not necessary and it used for security purpose as when the jwt won't be valid after changing the password. I'll fix the the problems you guys mentioned and add a middleware folder and necessary files

Sounds good, but please make sure that you only make the necessary edits for this issue for now, and after approving it, we can work on middleware stuff in another issue, because this issue is large enough as it is.

**Comment by tarik310** [comment]
I fixed the code and added a middleware section in the project.

**Review by zehraworks — APPROVED** [review]

**Review by OmarQaqish — APPROVED** [review]

**Pull request merged**
